/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pd1_lavrenovs;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class MainUserInterface extends javax.swing.JFrame {

    /**
     * Creates new form MainUserInterface
     */
    public MainUserInterface() {
        initComponents();
    }
    Admin admin = new Admin("admin", "admin", "parole");
    Student studentTest = new Student("student", "student", "parole");
    Test test = new Test();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegistracijasLogs = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        RegPogaReg = new javax.swing.JButton();
        AtpakalPogaReg = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        LietotajaIzveleLogs = new javax.swing.JDialog();
        PilditTestuPoga = new javax.swing.JButton();
        MainitParoliPoga = new javax.swing.JButton();
        ParaditRezultatuPoga = new javax.swing.JButton();
        LabelSveiki = new javax.swing.JLabel();
        TestaIzveidosanaLogs = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        JaunsJautaumsPoga = new javax.swing.JButton();
        DzestJautajumuPoga = new javax.swing.JButton();
        ParolesMainaLogs = new javax.swing.JDialog();
        ApstiprinatParolePoga = new javax.swing.JButton();
        AtpakalPogaParole = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        AtbildUzJautajumiemLogs = new javax.swing.JDialog();
        jCheckBox4 = new javax.swing.JCheckBox();
        TalakPoga = new javax.swing.JButton();
        DzestAtbildiPoga = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        LietotajaIzveleAdminLogs = new javax.swing.JDialog();
        VeidotTestuPoga = new javax.swing.JButton();
        MainitParoliPoga1 = new javax.swing.JButton();
        LabelSveikiAdmin = new javax.swing.JLabel();
        SaktTestuPoga = new javax.swing.JButton();
        SaktTestuAdminLogs = new javax.swing.JDialog();
        IerobezotTestuPoga = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        SaktTestuPogaAdmin = new javax.swing.JButton();
        SaktTestuLogs = new javax.swing.JDialog();
        SaktTestuPogaUser = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        RezultatiLogs = new javax.swing.JDialog();
        SaktTestuPogaUser1 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        GalvLogsLogin = new javax.swing.JLabel();
        GalvLogsParole = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        IelogosanasPoga = new javax.swing.JButton();
        RegistracijasPoga = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();

        RegistracijasLogs.setBackground(new java.awt.Color(255, 255, 255));
        RegistracijasLogs.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                RegistracijasLogsWindowClosing(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 153));
        jLabel3.setText("Vārds:");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 153));
        jLabel4.setText("Uzvārds:");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 153));
        jLabel5.setText("Lietotājvārds:");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 153));
        jLabel6.setText("Parole:");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 153, 153));
        jLabel7.setText("Parole(Atkārtoti):");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 153, 153));
        jLabel8.setText("E-pasts:");

        RegPogaReg.setBackground(new java.awt.Color(255, 204, 204));
        RegPogaReg.setForeground(new java.awt.Color(255, 102, 102));
        RegPogaReg.setText("Reģistrēties");
        RegPogaReg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegPogaRegMouseClicked(evt);
            }
        });

        AtpakalPogaReg.setBackground(new java.awt.Color(255, 204, 204));
        AtpakalPogaReg.setForeground(new java.awt.Color(255, 102, 102));
        AtpakalPogaReg.setText("Atpakaļ");
        AtpakalPogaReg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AtpakalPogaRegMouseClicked(evt);
            }
        });

        jTextField4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jTextField5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jTextField6.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jTextField7.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jTextField8.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jTextField9.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        javax.swing.GroupLayout RegistracijasLogsLayout = new javax.swing.GroupLayout(RegistracijasLogs.getContentPane());
        RegistracijasLogs.getContentPane().setLayout(RegistracijasLogsLayout);
        RegistracijasLogsLayout.setHorizontalGroup(
            RegistracijasLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistracijasLogsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RegistracijasLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistracijasLogsLayout.createSequentialGroup()
                        .addGroup(RegistracijasLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(28, 28, 28)
                        .addGroup(RegistracijasLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(30, Short.MAX_VALUE))
                    .addGroup(RegistracijasLogsLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(RegPogaReg, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(AtpakalPogaReg, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82))))
        );
        RegistracijasLogsLayout.setVerticalGroup(
            RegistracijasLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistracijasLogsLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(RegistracijasLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RegistracijasLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RegistracijasLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RegistracijasLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RegistracijasLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RegistracijasLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(RegistracijasLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AtpakalPogaReg, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegPogaReg, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        LietotajaIzveleLogs.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                LietotajaIzveleLogsWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                LietotajaIzveleLogsWindowOpened(evt);
            }
        });

        PilditTestuPoga.setBackground(new java.awt.Color(255, 204, 204));
        PilditTestuPoga.setForeground(new java.awt.Color(255, 102, 102));
        PilditTestuPoga.setText("Pildīt testu");
        PilditTestuPoga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PilditTestuPogaMouseClicked(evt);
            }
        });

        MainitParoliPoga.setBackground(new java.awt.Color(255, 204, 204));
        MainitParoliPoga.setForeground(new java.awt.Color(255, 102, 102));
        MainitParoliPoga.setText("Mainīt paroli");
        MainitParoliPoga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MainitParoliPogaMouseClicked(evt);
            }
        });

        ParaditRezultatuPoga.setBackground(new java.awt.Color(255, 204, 204));
        ParaditRezultatuPoga.setForeground(new java.awt.Color(255, 102, 102));
        ParaditRezultatuPoga.setText("Parādīt rezultatu");
        ParaditRezultatuPoga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ParaditRezultatuPogaMouseClicked(evt);
            }
        });

        LabelSveiki.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        LabelSveiki.setForeground(new java.awt.Color(255, 153, 153));
        LabelSveiki.setText("Sveiki \"Lietotājs\"");

        javax.swing.GroupLayout LietotajaIzveleLogsLayout = new javax.swing.GroupLayout(LietotajaIzveleLogs.getContentPane());
        LietotajaIzveleLogs.getContentPane().setLayout(LietotajaIzveleLogsLayout);
        LietotajaIzveleLogsLayout.setHorizontalGroup(
            LietotajaIzveleLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LietotajaIzveleLogsLayout.createSequentialGroup()
                .addGroup(LietotajaIzveleLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LietotajaIzveleLogsLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(LietotajaIzveleLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MainitParoliPoga, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PilditTestuPoga, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ParaditRezultatuPoga, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(LietotajaIzveleLogsLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(LabelSveiki)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        LietotajaIzveleLogsLayout.setVerticalGroup(
            LietotajaIzveleLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LietotajaIzveleLogsLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(LabelSveiki)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(ParaditRezultatuPoga, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(PilditTestuPoga, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(MainitParoliPoga, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        TestaIzveidosanaLogs.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                TestaIzveidosanaLogsWindowClosing(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 153, 153));
        jLabel10.setText("1. jautājums „Jautājuma teksts”");

        jCheckBox1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 153, 153));
        jCheckBox1.setText("1. atbilde");

        jCheckBox2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(255, 153, 153));
        jCheckBox2.setText("2. atbilde");

        jCheckBox3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jCheckBox3.setForeground(new java.awt.Color(255, 153, 153));
        jCheckBox3.setText("3. atbilde");

        JaunsJautaumsPoga.setBackground(new java.awt.Color(255, 204, 204));
        JaunsJautaumsPoga.setForeground(new java.awt.Color(255, 102, 102));
        JaunsJautaumsPoga.setText("Jauns jautājums");

        DzestJautajumuPoga.setBackground(new java.awt.Color(255, 204, 204));
        DzestJautajumuPoga.setForeground(new java.awt.Color(255, 102, 102));
        DzestJautajumuPoga.setText("Dzēst jautājumu");

        javax.swing.GroupLayout TestaIzveidosanaLogsLayout = new javax.swing.GroupLayout(TestaIzveidosanaLogs.getContentPane());
        TestaIzveidosanaLogs.getContentPane().setLayout(TestaIzveidosanaLogsLayout);
        TestaIzveidosanaLogsLayout.setHorizontalGroup(
            TestaIzveidosanaLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TestaIzveidosanaLogsLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(TestaIzveidosanaLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox1)
                    .addComponent(jLabel10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TestaIzveidosanaLogsLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(JaunsJautaumsPoga, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(DzestJautajumuPoga, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        TestaIzveidosanaLogsLayout.setVerticalGroup(
            TestaIzveidosanaLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TestaIzveidosanaLogsLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox1)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox2)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(TestaIzveidosanaLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JaunsJautaumsPoga, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DzestJautajumuPoga, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        ParolesMainaLogs.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                ParolesMainaLogsWindowClosing(evt);
            }
        });

        ApstiprinatParolePoga.setBackground(new java.awt.Color(255, 204, 204));
        ApstiprinatParolePoga.setForeground(new java.awt.Color(255, 102, 102));
        ApstiprinatParolePoga.setText("Apstiprināt");

        AtpakalPogaParole.setBackground(new java.awt.Color(255, 204, 204));
        AtpakalPogaParole.setForeground(new java.awt.Color(255, 102, 102));
        AtpakalPogaParole.setText("Atpakaļ");
        AtpakalPogaParole.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AtpakalPogaParoleMouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 153, 153));
        jLabel11.setText("Paroles maiņa");

        jTextField10.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });

        jTextField12.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });

        jTextField13.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 153, 153));
        jLabel12.setText("Pašreizējā parole:");

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 153, 153));
        jLabel13.setText("Jaunā parole:");

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 153, 153));
        jLabel14.setText("Jaunā parole (Atkārtoti):");

        javax.swing.GroupLayout ParolesMainaLogsLayout = new javax.swing.GroupLayout(ParolesMainaLogs.getContentPane());
        ParolesMainaLogs.getContentPane().setLayout(ParolesMainaLogsLayout);
        ParolesMainaLogsLayout.setHorizontalGroup(
            ParolesMainaLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ParolesMainaLogsLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(ParolesMainaLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ParolesMainaLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
            .addGroup(ParolesMainaLogsLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(ApstiprinatParolePoga, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AtpakalPogaParole, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(ParolesMainaLogsLayout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ParolesMainaLogsLayout.setVerticalGroup(
            ParolesMainaLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ParolesMainaLogsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(ParolesMainaLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ParolesMainaLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(ParolesMainaLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(ParolesMainaLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ApstiprinatParolePoga, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AtpakalPogaParole, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        AtbildUzJautajumiemLogs.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                AtbildUzJautajumiemLogsWindowClosing(evt);
            }
        });

        jCheckBox4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jCheckBox4.setForeground(new java.awt.Color(255, 153, 153));
        jCheckBox4.setText("3. atbilde");

        TalakPoga.setBackground(new java.awt.Color(255, 204, 204));
        TalakPoga.setForeground(new java.awt.Color(255, 102, 102));
        TalakPoga.setText("Tālāk");

        DzestAtbildiPoga.setBackground(new java.awt.Color(255, 204, 204));
        DzestAtbildiPoga.setForeground(new java.awt.Color(255, 102, 102));
        DzestAtbildiPoga.setText("Dzēst atbildi");

        jLabel15.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 153, 153));
        jLabel15.setText("1. jautājums „Jautājuma teksts”");

        jCheckBox5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jCheckBox5.setForeground(new java.awt.Color(255, 153, 153));
        jCheckBox5.setText("1. atbilde");

        jCheckBox6.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jCheckBox6.setForeground(new java.awt.Color(255, 153, 153));
        jCheckBox6.setText("2. atbilde");

        javax.swing.GroupLayout AtbildUzJautajumiemLogsLayout = new javax.swing.GroupLayout(AtbildUzJautajumiemLogs.getContentPane());
        AtbildUzJautajumiemLogs.getContentPane().setLayout(AtbildUzJautajumiemLogsLayout);
        AtbildUzJautajumiemLogsLayout.setHorizontalGroup(
            AtbildUzJautajumiemLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AtbildUzJautajumiemLogsLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(AtbildUzJautajumiemLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox4)
                    .addComponent(jCheckBox6)
                    .addComponent(jCheckBox5)
                    .addComponent(jLabel15))
                .addContainerGap(99, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AtbildUzJautajumiemLogsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(TalakPoga, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DzestAtbildiPoga, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        AtbildUzJautajumiemLogsLayout.setVerticalGroup(
            AtbildUzJautajumiemLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AtbildUzJautajumiemLogsLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox5)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox6)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(AtbildUzJautajumiemLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TalakPoga, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DzestAtbildiPoga, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        LietotajaIzveleAdminLogs.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                LietotajaIzveleAdminLogsWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                LietotajaIzveleAdminLogsWindowOpened(evt);
            }
        });

        VeidotTestuPoga.setBackground(new java.awt.Color(255, 204, 204));
        VeidotTestuPoga.setForeground(new java.awt.Color(255, 102, 102));
        VeidotTestuPoga.setText("Veidot testu");
        VeidotTestuPoga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VeidotTestuPogaMouseClicked(evt);
            }
        });

        MainitParoliPoga1.setBackground(new java.awt.Color(255, 204, 204));
        MainitParoliPoga1.setForeground(new java.awt.Color(255, 102, 102));
        MainitParoliPoga1.setText("Mainīt paroli");
        MainitParoliPoga1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MainitParoliPoga1MouseClicked(evt);
            }
        });

        LabelSveikiAdmin.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        LabelSveikiAdmin.setForeground(new java.awt.Color(255, 153, 153));
        LabelSveikiAdmin.setText("Sveiki \"Lietotājs\"");

        SaktTestuPoga.setBackground(new java.awt.Color(255, 204, 204));
        SaktTestuPoga.setForeground(new java.awt.Color(255, 102, 102));
        SaktTestuPoga.setText("Sākt testu");
        SaktTestuPoga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaktTestuPogaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout LietotajaIzveleAdminLogsLayout = new javax.swing.GroupLayout(LietotajaIzveleAdminLogs.getContentPane());
        LietotajaIzveleAdminLogs.getContentPane().setLayout(LietotajaIzveleAdminLogsLayout);
        LietotajaIzveleAdminLogsLayout.setHorizontalGroup(
            LietotajaIzveleAdminLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LietotajaIzveleAdminLogsLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(LietotajaIzveleAdminLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelSveikiAdmin)
                    .addGroup(LietotajaIzveleAdminLogsLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(LietotajaIzveleAdminLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SaktTestuPoga, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MainitParoliPoga1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VeidotTestuPoga, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        LietotajaIzveleAdminLogsLayout.setVerticalGroup(
            LietotajaIzveleAdminLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LietotajaIzveleAdminLogsLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(LabelSveikiAdmin)
                .addGap(18, 18, 18)
                .addComponent(SaktTestuPoga, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(VeidotTestuPoga, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(MainitParoliPoga1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        SaktTestuAdminLogs.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                SaktTestuAdminLogsWindowClosing(evt);
            }
        });

        IerobezotTestuPoga.setBackground(new java.awt.Color(255, 204, 204));
        IerobezotTestuPoga.setForeground(new java.awt.Color(255, 102, 102));
        IerobezotTestuPoga.setText("Ierobežot testu");

        jLabel17.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 153, 153));
        jLabel17.setText("Tests \"nosaukums\"");

        SaktTestuPogaAdmin.setBackground(new java.awt.Color(255, 204, 204));
        SaktTestuPogaAdmin.setForeground(new java.awt.Color(255, 102, 102));
        SaktTestuPogaAdmin.setText("Sākt testu");

        javax.swing.GroupLayout SaktTestuAdminLogsLayout = new javax.swing.GroupLayout(SaktTestuAdminLogs.getContentPane());
        SaktTestuAdminLogs.getContentPane().setLayout(SaktTestuAdminLogsLayout);
        SaktTestuAdminLogsLayout.setHorizontalGroup(
            SaktTestuAdminLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SaktTestuAdminLogsLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(27, 27, 27))
            .addGroup(SaktTestuAdminLogsLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(SaktTestuAdminLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(IerobezotTestuPoga, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SaktTestuPogaAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SaktTestuAdminLogsLayout.setVerticalGroup(
            SaktTestuAdminLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SaktTestuAdminLogsLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(SaktTestuPogaAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(IerobezotTestuPoga, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        SaktTestuLogs.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                SaktTestuLogsWindowClosing(evt);
            }
        });

        SaktTestuPogaUser.setBackground(new java.awt.Color(255, 204, 204));
        SaktTestuPogaUser.setForeground(new java.awt.Color(255, 102, 102));
        SaktTestuPogaUser.setText("Sākt testu");
        SaktTestuPogaUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaktTestuPogaUserMouseClicked(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 153, 153));
        jLabel18.setText("Tests \"nosaukums\"");

        javax.swing.GroupLayout SaktTestuLogsLayout = new javax.swing.GroupLayout(SaktTestuLogs.getContentPane());
        SaktTestuLogs.getContentPane().setLayout(SaktTestuLogsLayout);
        SaktTestuLogsLayout.setHorizontalGroup(
            SaktTestuLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SaktTestuLogsLayout.createSequentialGroup()
                .addGroup(SaktTestuLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SaktTestuLogsLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel18))
                    .addGroup(SaktTestuLogsLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(SaktTestuPogaUser, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        SaktTestuLogsLayout.setVerticalGroup(
            SaktTestuLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SaktTestuLogsLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SaktTestuPogaUser, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        RezultatiLogs.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                RezultatiLogsWindowClosing(evt);
            }
        });

        SaktTestuPogaUser1.setBackground(new java.awt.Color(255, 204, 204));
        SaktTestuPogaUser1.setForeground(new java.awt.Color(255, 102, 102));
        SaktTestuPogaUser1.setText("Aizvērt");

        jLabel19.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 153, 153));
        jLabel19.setText("Rezultāti");

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 153, 153));
        jLabel20.setText("Procenti: X%");

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 153, 153));
        jLabel21.setText("Atzīme: A");

        javax.swing.GroupLayout RezultatiLogsLayout = new javax.swing.GroupLayout(RezultatiLogs.getContentPane());
        RezultatiLogs.getContentPane().setLayout(RezultatiLogsLayout);
        RezultatiLogsLayout.setHorizontalGroup(
            RezultatiLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RezultatiLogsLayout.createSequentialGroup()
                .addGroup(RezultatiLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RezultatiLogsLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel19))
                    .addGroup(RezultatiLogsLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(RezultatiLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(SaktTestuPogaUser1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        RezultatiLogsLayout.setVerticalGroup(
            RezultatiLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RezultatiLogsLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel21)
                .addGap(35, 35, 35)
                .addComponent(SaktTestuPogaUser1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        GalvLogsLogin.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        GalvLogsLogin.setForeground(new java.awt.Color(255, 153, 153));
        GalvLogsLogin.setText("Lietotājvārds:");

        GalvLogsParole.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        GalvLogsParole.setForeground(new java.awt.Color(255, 153, 153));
        GalvLogsParole.setText("Parole:");

        jTextField1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        IelogosanasPoga.setBackground(new java.awt.Color(255, 204, 204));
        IelogosanasPoga.setForeground(new java.awt.Color(255, 102, 102));
        IelogosanasPoga.setText("Ielogoties");
        IelogosanasPoga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IelogosanasPogaMouseClicked(evt);
            }
        });

        RegistracijasPoga.setBackground(new java.awt.Color(255, 204, 204));
        RegistracijasPoga.setForeground(new java.awt.Color(255, 102, 102));
        RegistracijasPoga.setText("Reģistrēties");
        RegistracijasPoga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistracijasPogaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(GalvLogsParole)
                            .addComponent(GalvLogsLogin)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(IelogosanasPoga, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(RegistracijasPoga, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPasswordField1))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GalvLogsLogin)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GalvLogsParole)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IelogosanasPoga, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegistracijasPoga, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistracijasPogaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistracijasPogaMouseClicked
        RegistracijasLogs.setBounds(0, 0, 400, 400);
        this.setVisible(false);
        RegistracijasLogs.setVisible(true);

    }//GEN-LAST:event_RegistracijasPogaMouseClicked

    private void RegistracijasLogsWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_RegistracijasLogsWindowClosing
        RegistracijasLogs.dispose();
        this.setVisible(true);
    }//GEN-LAST:event_RegistracijasLogsWindowClosing

    private void AtpakalPogaRegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AtpakalPogaRegMouseClicked
        RegistracijasLogs.dispose();
        this.setVisible(true);
    }//GEN-LAST:event_AtpakalPogaRegMouseClicked

    private void IelogosanasPogaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IelogosanasPogaMouseClicked
        try {
            String userLogin = jTextField1.getText().trim();
            String userPassword = jPasswordField1.getText();

            String role = User.enter(userLogin, userPassword);

            if (role == null) {
                JOptionPane.showMessageDialog(null, "Nepareizs lietotājvārds vai parole");
                return;
            }

            switch (role) {
                case "student":
                    LietotajaIzveleLogs.pack();
                    LietotajaIzveleLogs.setLocationRelativeTo(null);
                    LietotajaIzveleLogs.setVisible(true);
                    break;
                case "admin":
                    LietotajaIzveleAdminLogs.setSize(400, 270);
                    LietotajaIzveleAdminLogs.setLocationRelativeTo(null);
                    LietotajaIzveleAdminLogs.setVisible(true);
                    break;
                default:
                    JOptionPane.showMessageDialog(null, "Nezināma lietotāja loma");
                    break;
            }

        } catch (java.sql.SQLException ex) {
            JOptionPane.showMessageDialog(null, "Savienojuma kļūda ar datubāzi");
            Logger.getLogger(MainUserInterface.class.getName())
                    .log(Level.SEVERE, "Datubāzes kļūda", ex);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Nezināma kļūda programmā");
            Logger.getLogger(MainUserInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_IelogosanasPogaMouseClicked

    private void LietotajaIzveleLogsWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_LietotajaIzveleLogsWindowClosing
        LietotajaIzveleLogs.dispose();
        this.setVisible(true);
    }//GEN-LAST:event_LietotajaIzveleLogsWindowClosing

    private void ParaditRezultatuPogaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ParaditRezultatuPogaMouseClicked
        RezultatiLogs.setBounds(0, 0, 200, 200);
        LietotajaIzveleLogs.setVisible(false);
        RezultatiLogs.setVisible(true);
    }//GEN-LAST:event_ParaditRezultatuPogaMouseClicked

    private void RezultatiLogsWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_RezultatiLogsWindowClosing
        RezultatiLogs.dispose();
        LietotajaIzveleLogs.setVisible(true);
    }//GEN-LAST:event_RezultatiLogsWindowClosing

    private void MainitParoliPogaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainitParoliPogaMouseClicked
        ParolesMainaLogs.setBounds(0, 0, 500, 300);
        LietotajaIzveleLogs.setVisible(false);
        ParolesMainaLogs.setVisible(true);
    }//GEN-LAST:event_MainitParoliPogaMouseClicked

    private void ParolesMainaLogsWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_ParolesMainaLogsWindowClosing
        ParolesMainaLogs.dispose();
        LietotajaIzveleLogs.setVisible(true);
    }//GEN-LAST:event_ParolesMainaLogsWindowClosing

    private void AtpakalPogaParoleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AtpakalPogaParoleMouseClicked
        ParolesMainaLogs.dispose();
        LietotajaIzveleLogs.setVisible(true);
    }//GEN-LAST:event_AtpakalPogaParoleMouseClicked

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void PilditTestuPogaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PilditTestuPogaMouseClicked
        SaktTestuLogs.setBounds(0, 0, 285, 150);
        LietotajaIzveleLogs.setVisible(false);
        SaktTestuLogs.setVisible(true);
    }//GEN-LAST:event_PilditTestuPogaMouseClicked

    private void SaktTestuLogsWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_SaktTestuLogsWindowClosing
        SaktTestuLogs.dispose();
        LietotajaIzveleLogs.setVisible(true);
    }//GEN-LAST:event_SaktTestuLogsWindowClosing

    private void SaktTestuPogaUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaktTestuPogaUserMouseClicked
        AtbildUzJautajumiemLogs.setBounds(0, 0, 400, 400);
        SaktTestuLogs.setVisible(false);
        AtbildUzJautajumiemLogs.setVisible(true);
    }//GEN-LAST:event_SaktTestuPogaUserMouseClicked

    private void AtbildUzJautajumiemLogsWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_AtbildUzJautajumiemLogsWindowClosing
        AtbildUzJautajumiemLogs.dispose();
        LietotajaIzveleLogs.setVisible(true);
    }//GEN-LAST:event_AtbildUzJautajumiemLogsWindowClosing

    private void MainitParoliPoga1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainitParoliPoga1MouseClicked
        ParolesMainaLogs.setBounds(0, 0, 500, 300);
        LietotajaIzveleAdminLogs.setVisible(false);
        ParolesMainaLogs.setVisible(true);
    }//GEN-LAST:event_MainitParoliPoga1MouseClicked

    private void LietotajaIzveleAdminLogsWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_LietotajaIzveleAdminLogsWindowClosing
        LietotajaIzveleAdminLogs.dispose();
        this.setVisible(true);
    }//GEN-LAST:event_LietotajaIzveleAdminLogsWindowClosing

    private void SaktTestuPogaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaktTestuPogaMouseClicked
        SaktTestuAdminLogs.setBounds(0, 0, 400, 400);
        LietotajaIzveleAdminLogs.setVisible(false);
        SaktTestuAdminLogs.setVisible(true);
    }//GEN-LAST:event_SaktTestuPogaMouseClicked

    private void VeidotTestuPogaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VeidotTestuPogaMouseClicked
        TestaIzveidosanaLogs.setBounds(0, 0, 400, 400);
        LietotajaIzveleAdminLogs.setVisible(false);
        TestaIzveidosanaLogs.setVisible(true);
    }//GEN-LAST:event_VeidotTestuPogaMouseClicked

    private void TestaIzveidosanaLogsWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_TestaIzveidosanaLogsWindowClosing
        TestaIzveidosanaLogs.dispose();
        LietotajaIzveleAdminLogs.setVisible(true);
    }//GEN-LAST:event_TestaIzveidosanaLogsWindowClosing

    private void SaktTestuAdminLogsWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_SaktTestuAdminLogsWindowClosing
        SaktTestuAdminLogs.dispose();
        LietotajaIzveleAdminLogs.setVisible(true);
    }//GEN-LAST:event_SaktTestuAdminLogsWindowClosing

    private void RegPogaRegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegPogaRegMouseClicked
        try {
            String name = jTextField4.getText().trim();
            String surname = jTextField5.getText().trim();
            String login = jTextField6.getText().trim();
            String pass1 = jTextField7.getText();
            String pass2 = jTextField9.getText();

            if (name.isEmpty() || surname.isEmpty() || login.isEmpty() || pass1.isEmpty() || pass2.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Aizpildi visus laukus!");
                return;
            }

            if (!pass1.equals(pass2)) {
                JOptionPane.showMessageDialog(null, "Paroles nesakrīt!");
                return;
            }

            boolean ok = User.registerStudent(name, surname, login, pass1);

            if (!ok) {
                JOptionPane.showMessageDialog(null, "Šāds lietotājvārds jau eksistē!");
                return;
            }

            JOptionPane.showMessageDialog(null, "Reģistrācija veiksmīga!");
            dispose();
            this.setVisible(true);
            RegistracijasLogs.setVisible(false);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Nezināma kļūda programmā");
            Logger.getLogger(MainUserInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_RegPogaRegMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowOpened

    private void LietotajaIzveleLogsWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_LietotajaIzveleLogsWindowOpened
        this.setVisible(false);
        LabelSveiki.setText("Sveiki " + studentTest.name + "!");
    }//GEN-LAST:event_LietotajaIzveleLogsWindowOpened

    private void LietotajaIzveleAdminLogsWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_LietotajaIzveleAdminLogsWindowOpened
        this.setVisible(false);
        LabelSveikiAdmin.setText("Sveiki " + admin.name + "!");
    }//GEN-LAST:event_LietotajaIzveleAdminLogsWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUserInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ApstiprinatParolePoga;
    private javax.swing.JDialog AtbildUzJautajumiemLogs;
    private javax.swing.JButton AtpakalPogaParole;
    private javax.swing.JButton AtpakalPogaReg;
    private javax.swing.JButton DzestAtbildiPoga;
    private javax.swing.JButton DzestJautajumuPoga;
    private javax.swing.JLabel GalvLogsLogin;
    private javax.swing.JLabel GalvLogsParole;
    private javax.swing.JButton IelogosanasPoga;
    private javax.swing.JButton IerobezotTestuPoga;
    private javax.swing.JButton JaunsJautaumsPoga;
    private javax.swing.JLabel LabelSveiki;
    private javax.swing.JLabel LabelSveikiAdmin;
    private javax.swing.JDialog LietotajaIzveleAdminLogs;
    private javax.swing.JDialog LietotajaIzveleLogs;
    private javax.swing.JButton MainitParoliPoga;
    private javax.swing.JButton MainitParoliPoga1;
    private javax.swing.JButton ParaditRezultatuPoga;
    private javax.swing.JDialog ParolesMainaLogs;
    private javax.swing.JButton PilditTestuPoga;
    private javax.swing.JButton RegPogaReg;
    private javax.swing.JDialog RegistracijasLogs;
    private javax.swing.JButton RegistracijasPoga;
    private javax.swing.JDialog RezultatiLogs;
    private javax.swing.JDialog SaktTestuAdminLogs;
    private javax.swing.JDialog SaktTestuLogs;
    private javax.swing.JButton SaktTestuPoga;
    private javax.swing.JButton SaktTestuPogaAdmin;
    private javax.swing.JButton SaktTestuPogaUser;
    private javax.swing.JButton SaktTestuPogaUser1;
    private javax.swing.JButton TalakPoga;
    private javax.swing.JDialog TestaIzveidosanaLogs;
    private javax.swing.JButton VeidotTestuPoga;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
